import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
   "~/dotfiles/alacritty/catppuccin-mocha.toml"
]

[colors.primary]
background = "0x1e1e1e"
foreground = "0xc5c8c6"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window]
opacity = 0.7

[window.padding]
x = 15
y = 15

[selection]
save_to_clipboard = true

